apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  selector:
    app: mongodb
  ports:
  - protocol: TCP
    port: 27017        #Porta que será exposta no service
    targetPort: 27017  #Porta do container
  type: ClusterIP